server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3

spring:
  application:
    name: department-service
    skipSslValidation: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

messages:
  prop: test
  name: ConfigServer8088
